graphql:
  graphiql:
    enabled: true

server:
  port: 8286
  servlet:
    session:
      timeout: 2m
    context-path: "/app"

spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: CLIENT-ID
          clientSecret: SECRET
          scope:
           - email
           - profile
  devtools:
    restart:
      exclude: logs/**,static/**,public/**
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        
secret: randomsecret
