# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    defaults:
        run:
          working-directory: app/sue_tutor/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
    - run: flutter pub get
    - run: flutter gen-l10n
    - run: flutter build apk
    - uses: actions/upload-artifact@v2
      with:
        name: apk-release
        path: app/sue_tutor/build/app/outputs/flutter-apk/app-release.apk
        
    - run: flutter build appbundle
    - uses: actions/upload-artifact@v2
      with:
        name: abb-release
        path: app/sue_tutor/build/app/outputs/bundle/release/app-release.aab
        
    - run: flutter build web
    
    
  ios:
    defaults:
        run:
          working-directory: app/sue_tutor/
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
    - run: flutter pub get
    - run: flutter gen-l10n
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v2
      with:
        name: ios-app-release
        path: /Users/runner/work/sue-tutor/sue-tutor/app/sue_tutor/build/ios/iphoneos/Runner.app
